### ISSUE TITLE
Installation error on macOS with Julia 0.6.2

### ISSUE THREAD

**Issue by giob1994** [JuliaGPU/ArrayFire.jl#205]
Hi,

I am using Julia v0.6.2 and I just installed ArrayFire v3.6.0. My macOS is High Sierra 10.13.4.

When I try `using ArrayFire`, precompilation of the package fails with the following error:

```
INFO: Precompiling module ArrayFire.
ERROR: LoadError: error compiling __init__: could not load library "libaf"
dlopen(libaf.dylib, 1): image not found
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /Users/giovannib/.julia/v0.6/ArrayFire/src/ArrayFire.jl, in expression starting on line 12
Failed to precompile ArrayFire to /Users/giovannib/.julia/lib/v0.6/ArrayFire.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
```

I checked the ArrayFire directory at `/opt/arrayfire/lib` and everything seems fine, so I am not sure what to do...

**Comment by gaika** [comment]
Is `/opt/arrayfire/lib` in `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH`? Is `libaf.dylib` in `/opt/arrayfire/lib` ?

**Comment by gaika** [comment]
Do `ArrayFire` examples work?

**Comment by giob1994** [comment]
This is my /opt/arrayfire/lib folder:
```
~$ ls /opt/arrayfire/lib
libaf.3.6.0.dylib*        libafopencl.dylib@        libmkl_avx.dylib
libaf.3.dylib@            libcublas.dylib.9.1       libmkl_avx2.dylib
libaf.dylib@              libcudart.dylib.9.1       libmkl_avx512.dylib
libafcpu.3.6.0.dylib*     libcufft.dylib.9.1        libmkl_core.dylib
libafcpu.3.dylib@         libcusolver.dylib.9.1     libmkl_intel_lp64.dylib
libafcpu.dylib@           libcusparse.dylib.9.1     libmkl_mc.dylib
libafcuda.3.6.0.dylib*    libforge.1.1.0.dylib      libmkl_mc3.dylib
libafcuda.3.dylib@        libforge.1.dylib@         libmkl_tbb_thread.dylib
libafcuda.dylib@          libforge.dylib@           libnvrtc-builtins.dylib
libafopencl.3.6.0.dylib*  libglbinding.2.1.4.dylib  libnvrtc.dylib.9.1
libafopencl.3.dylib@      libglbinding.2.dylib@     libtbb.dylib
```

and I am not sure how to check if `/opt/arrayfire/lib` is in `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH` as I haven't seen it mentioned in the installation instructions.

**Comment by gaika** [comment]
> and I am not sure how to check if /opt/arrayfire/lib is in LD_LIBRARY_PATH or DYLD_LIBRARY_PATH as I haven't seen it mentioned in the installation instructions.

`echo $LD_LIBRARY_PATH $DYLD_LIBRARY_PATH | grep -i arrayfire` 
`otool -L af`

**Comment by gaika** [comment]
Can you try
`julia> push!(Libdl.DL_LOAD_PATH, "/opt/arrayfire/lib"); Pkg.build("ArrayFire")` ?

**Comment by giob1994** [comment]
This runs fine:

> `julia> push!(Libdl.DL_LOAD_PATH, "/opt/arrayfire/lib"); Pkg.build("ArrayFire")`
 
but executing `using ArrayFire` now gives me another error:

```
INFO: Recompiling stale cache file /Users/giovannib/.julia/lib/v0.6/ArrayFire.ji for module ArrayFire.
ERROR: InitError: ArrayFire Error (501) : Failed to load dynamic library. 
Error in af_err unified::AFSymbolManager::call(const char *, CalleeArgs...) [CalleeArgs = <>]
In file src/api/unified/symbol_manager.hpp:67
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

Stacktrace:
 [1] _error(::UInt32) at /Users/giovannib/.julia/v0.6/ArrayFire/src/util.jl:87
 [2] __init__() at /Users/giovannib/.julia/v0.6/ArrayFire/src/util.jl:65
 [3] _include_from_serialized(::String) at ./loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [5] _require(::Symbol) at ./loading.jl:464
 [6] require(::Symbol) at ./loading.jl:405
during initialization of module ArrayFire
```

**Comment by gaika** [comment]
Add `DYLD_LIBRARY_PATH=/opt/arrayfire/lib` to your `.bashrc` and make sure julia sees it `julia> ENV["DYLD_LIBRARY_PATH"]`, actually try setting it in julia with `ENV["DYLD_LIBRARY_PATH"] = "/opt/arrayfire/lib"` and see if it works.

If this fails that means that some other dependencies are missing, `otool` is your friend to figure out which ones:

`$ export DYLD_LIBRARY_PATH=/opt/arrayfire/lib ; otool -L af`

**Comment by rveltz** [comment]
I have the same issue. Did you find a solution?

**Comment by giob1994** [comment]
Not really...
 
Also tried with adding `DYLD_LIBRARY_PATH=/opt/arrayfire/lib` in my `.bash_profile` file in my users folder: nothing changes.

If I then run `ENV["DYLD_LIBRARY_PATH"]`, Julia tells me:
```
ERROR: KeyError: key "DYLD_LIBRARY_PATH" not found
Stacktrace:
 [1] access_env(::Base.##288#289, ::String) at ./env.jl:45
 [2] getindex(::Base.EnvHash, ::String) at ./env.jl:78
```

And even doing `ENV["DYLD_LIBRARY_PATH"] = "/opt/arrayfire/lib"` and then `using ArrayFire`, still gives me the error:
```
ERROR: InitError: error compiling __init__: could not load library "libaf"
dlopen(libaf.dylib, 1): image not found
Stacktrace:
 [1] _include_from_serialized(::String) at ./loading.jl:157
 [2] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [3] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
```

I am not sure what else to do.

**Comment by rveltz** [comment]
Do you have a new mac with SIP?

**Comment by giob1994** [comment]
I guess this is the case since my MacBook Pro is the 13-inch 2016 (with Touch Bar).

**Comment by rveltz** [comment]
I compiled it from sources and it worked

**Comment by beOn** [comment]
Having the same issue. @rveltz - did you install into the default location? @giob1994, did you ever find a solution?

**Comment by giob1994** [comment]
@beOn I did not try again after @rveltz suggested compiling from source: I am not willing to spend my time compiling stuff just to use a library... Also, in Julia 0.6.4 I had to manually remove ArrayFire.jl as it would complain that it was not compatible with v0.6 anymore...

**Comment by VasylHafych** [comment]
Hello everyone, 

I am experiencing the same issue as @giob1994 . As @gaika has suggested [here](https://github.com/JuliaComputing/ArrayFire.jl/issues/205#issuecomment-386649781), I have set up both` LD_LIBRARY_PATH `and `DYLD_LIBRARY_PATH` to the ArrayFier library path `"/opt/arrayfire/lib"` using `~/.bashrc`. I have also turned off System Integrity Protection on Mac, as it has been discussed [here](https://github.com/nteract/nteract/issues/1523#issuecomment-284027093). I can see now that the `LD_LIBRARY_PATH` is referencing a correct path by running `ENV["LD_LIBRARY_PATH"]` from Jupyter Notebook:
```
Julia> ENV["LD_LIBRARY_PATH"]
"/opt/arrayfire/lib:" 
```
However, when I try `using ArrayFire` or `Pkg.test("ArrayFire")` I am getting the following error:
```
InitError: ArrayFire Error (501) : Failed to load dynamic library. 
Error in af_err unified::AFSymbolManager::call(const char *, CalleeArgs...) [CalleeArgs = <>]
In file src/api/unified/symbol_manager.hpp:60
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

during initialization of module ArrayFire

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] _error(::UInt32) at /Users/hafych/.julia/packages/ArrayFire/4SkOz/src/util.jl:87
 [3] afinit at /Users/hafych/.julia/packages/ArrayFire/4SkOz/src/wrap.jl:996 [inlined]
 [4] __init__() at /Users/hafych/.julia/packages/ArrayFire/4SkOz/src/util.jl:65
 [5] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:627
 [6] macro expansion at ./logging.jl:312 [inlined]
 [7] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:698
 [8] _require(::Base.PkgId) at ./loading.jl:931
 [9] require(::Base.PkgId) at ./loading.jl:852
 [10] macro expansion at ./logging.jl:311 [inlined]
 [11] require(::Module, ::Symbol) at ./loading.jl:834
 [12] top-level scope at In[1]:1
```

I have tried this on **Julia 1.0.0** and **Julia 0.6.4** and the issue remains the same. I am using **"ArrayFire"        => v"0.7.0"** and macOS High Sierra 10.13.6 (MacBook Pro (13-inch, 2016)). 

What else should I do to figure out this issue? 

Thank you in advance!
Vasyl

**Comment by lstagner** [comment]
I had the same error on Julia 1.0.2. I compiled arrayfire from source and now I get a different error; it segfaults during precompilation on ArrayFire.jl master.
```
julia> using ArrayFire
[ Info: Precompiling ArrayFire [b19378d9-d87a-599a-927f-45f220a2c452]

signal (11): Segmentation fault: 11
in expression starting at /Users/lstagner/.julia/packages/ArrayFire/sLOn9/src/ArrayFire.jl:3
unknown function (ip: 0xffffffffffffffff)
Allocations: 1362092 (Pool: 1361772; Big: 320); GC: 2
ERROR: Failed to precompile ArrayFire [b19378d9-d87a-599a-927f-45f220a2c452] to /Users/lstagner/.julia/compiled/v1.0/ArrayFire/SIACH.ji.

julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by lstagner** [comment]
For some reason its working now. `¯\_(ツ)_/¯`

**Comment by xinkai-zhou** [comment]
The same problem persists. I installed ArrayFire from binary, and set `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` as mentioned above, but it still does not work, same error message:

```
InitError: error compiling __init__: could not load library "libaf"
dlopen(libaf.dylib, 1): image not found
during initialization of module ArrayFire
```

Here is my version info.

```
Julia Version 1.1.0
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```
