### ISSUE TITLE
Move to JuliaGPU org?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/ArrayFire.jl#231]
Does it make sense to move this package to the JuliaGPU org?

**Comment by gaika** [comment]
https://github.com/JuliaComputing/ArrayFire.jl/issues/165 -  yes

**Comment by ViralBShah** [comment]
@gaika Would it be possible for you to update the URLs in the relevant places? Thank you.

**Comment by gaika** [comment]
First github repo ownership has to be transferred, then all URLs can be updated.

**Comment by ViralBShah** [comment]
No urgency, since github will keep redirecting the URLs for a long time.
