### ISSUE TITLE
AFArray is not a subtype of AbstractArray in Julia 1.0.3

### ISSUE THREAD

**Issue by haruki-msl** [JuliaGPU/ArrayFire.jl#233]
The following code returns false.

```
using ArrayFire;
A = rand(10, 10);
typeof(A) <: AbstractArray # This returns true.
B = AFArray(A);
typeof(B) <: AbstractArray # This returns false.
```
Even `AFArray <: AbstractArray` returns false. This is inconvenient as functions defined to take AbstractArray type as arguments cannot be used.

** Julia Version **
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by gaika** [comment]
Usually, it causes more problems than it solves, but you can try

```
] dev ArrayFire
```
And uncomment
https://github.com/JuliaGPU/ArrayFire.jl/blob/a7c6dbe30a99b80de88572c14036cfe056fb156d/src/array.jl#L1

If that's a function you control, usually it is better to write it in a generic way so it doesn't rely on the type at all. 

If that's a function in a standard library usually it is better to add it to ArrayFire explicitly 

Which one is it for you?

**Comment by haruki-msl** [comment]
I uncommented the line you mentioned, since I had a function that can only take an argument of AbstractArray type. It sort of worked. Thank you for the help.
