### ISSUE TITLE
memory issues

### ISSUE THREAD

**Issue by michaelbenton** [JuliaGPU/ArrayFire.jl#248]
consider the following: 

m = 500;
n = 500;
k = 10;
s = Int64(1e8);

a = rand(AFArray,m,n,k);
x1 = rand(AFArray,s).*m;
x2 = rand(AFArray,s).*n;

function sumInterp(a,x1,x2)
extrapVal = convert(Float32,0);
methodInterp = AF_INTERP_LINEAR;
out = zeros(AFArray{Float32},length(x1));
siz = size(a);
k = siz[3];
for i = 1:k
out += approx2(a[:,:,i],x1, x2,methodInterp,extrapVal);
end
return out
end

@time out = sumInterp(a,x1,x2);

it's an operation to interpolate multiple images at the same location and add up what comes out of the interpolation. I could avoid the loop for small enough interpolations, (approx2 allows simultaneous interpolation into many 2d images)  but no GPU has enough VRAM for the size of interpolations my application calls for, so I have to loop over. The same script can be run in MATLAB with approx2 switched out for interpn and some other small syntactic changes, and it runs 10x faster. Why is that? well, immediately after launching arrayfire the first few loops of this are very fast, 10x faster than MATLAB, (100 us vs 1 ms)  but windows task manager shows gpu memory useage fill up immediately, and once full, every iteration of the loop takes a ton of time. 

every time "out += approx2(a[:,:,i],x1, x2,methodInterp,extrapVal);"   is run, another large chunk of vram is taken

My question becomes, how do I rewrite the above such that no new memory allocations are made on a new step (so that no gc has to take place)?

**Comment by whymusticode** [comment]
out = zeros(AFArray{Float32},length(x1));
for i = 1:k
    finalize(tmp)
    tmp = approx2(a[:,:,i],x1, x2,methodInterp,extrapVal);
    out += tmp;
end

^ this works
